name: Android Build APK

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
        env: 
         sign.key.password: ${{secrets.sign_key_password}}
         sign.key.alias: ${{secrets.sign_key_alias}}
         sign.key.path: ${{secrets.sign_key_path}}
         g.license.key: ${{secrets.g_license_key}}
         google.services.json: ${{secrets.google_services_json}}
         key.url: ${{secrets.key_url}}
         local.properties.url: ${{secrets.local_properties_url}}
         debug.google.services.json: ${{secrets.debug_google_services_json}}

  apk:
    name: Generate APK
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
        env: 
         sign.key.password: ${{secrets.sign_key_password}}
         sign.key.alias: ${{secrets.sign_key_alias}}
         sign.key.path: ${{secrets.sign_key_path}}
         g.license.key: ${{secrets.g_license_key}}
         google.services.json: ${{secrets.google_services_json}}
         key.url: ${{secrets.key_url}}
         local.properties.url: ${{secrets.local_properties_url}}
         debug.google.services.json: ${{secrets.debug_google_services_json}}

      - name: Upload Master APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/master/debug/app-master-debug.apk
          
      - name: Upload Galaxy APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/galaxy/debug/app-galaxy-debug.apk
